version: "2.4"
services:

  bacnet:
    image: amd64/nube-edge-connector-bacnet-simulator:${IOT_VERSION}
    mem_limit: 480m
    cpuset: "0"
    environment:
      JVM_OPTS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+UseContainerSupport -XX:+UseSerialGC -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:MaxRAM=395m -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -Xss256k -XX:ActiveProcessorCount=0
    ports:
      - ${BACNET_PORT}:47808/udp
    volumes:
      - bacnet-data:/data
      - ./engine/bacnet-simulator.json:/app/conf/simulator.json

volumes:
  bacnet-data:
    driver: local
