version: "2.4"
services:

  bacnet-java-simulator:
    image: ${PREFIX_IMG}/edge-connector-bacnet-simulator:${IOT_VERSION}
    mem_limit: 480m
    cpuset: "0"
    environment:
      JVM_OPTS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+UseContainerSupport -XX:+UseSerialGC -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:MaxRAM=395m -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -Xss256k -XX:ActiveProcessorCount=0
    volumes:
      - bacnet-data:/data
    networks:
      - bacnet-n1

  bacnet-simulator-for-java:
    image: c-bacnet
    mem_limit: 56m
    environment:
      DEVICE_NUMBER: 222
    command: ["perl", "./simulator.pl"]
    networks:
      - bacnet-n1

  bacnet-server-n1:
    image: c-bacnet
    mem_limit: 56m
    command: ["bacserv", "200001"]
    networks:
      - bacnet-n1

  bacnet-server-n2:
    image: c-bacnet
    mem_limit: 56m
    command: ["bacserv", "200002"]
    networks:
      - bacnet-n2

  bacnet-simulator-for-c:
    image: c-bacnet
    mem_limit: 56m
    environment:
      DEVICE_NUMBER: 200001
    command: ["perl", "./simulator.pl"]
    networks:
      - bacnet-n2

#   bacnet-py-simulator:
#     image: py-bacnet
#     mem_limit: 56m
#     networks:
#       - bacnet-n3

#   bacnet-simulator-for-py:
#     image: c-bacnet
#     mem_limit: 56m
#     environment:
#       DEVICE_NUMBER: 456
#     command: ["perl", "./simulator.pl"]
#     networks:
#       - bacnet-n3

volumes:
  bacnet-data:
    driver: local

networks:
  bacnet-n1:
    driver: bridge
  bacnet-n2:
    driver: bridge
#   bacnet-n3:
#     driver: bridge
