version: "2.4"

services:

  ditto-policies:
    init: true
    image: eclipse/ditto-policies:${DITTO_VERSION:-latest}
    mem_limit: 384m
    networks:
      default:
        aliases:
          - ditto-cluster
    environment:
      - TZ=UTC
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError
      - REMOTING_IDLE_CPU_LEVEL=1
      - MONGO_DB_URI=mongodb://ditto:ditto@mongo:27017/ditto

  ditto-things:
    init: true
    image: eclipse/ditto-things:${DITTO_VERSION:-latest}
    mem_limit: 512m
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - ditto-policies
    environment:
      - TZ=UTC
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError
      - REMOTING_IDLE_CPU_LEVEL=1
      - MONGO_DB_URI=mongodb://ditto:ditto@mongo:27017/ditto

  ditto-things-search:
    init: true
    image: eclipse/ditto-things-search:${DITTO_VERSION:-latest}
    mem_limit: 512m
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - ditto-policies
    environment:
      - TZ=UTC
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError
      - REMOTING_IDLE_CPU_LEVEL=1
      - MONGO_DB_URI=mongodb://ditto:ditto@mongo:27017/ditto

  ditto-concierge:
    init: true
    image: eclipse/ditto-concierge:${DITTO_VERSION:-latest}
    mem_limit: 384m
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - ditto-policies
    environment:
      - TZ=UTC
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError
      - REMOTING_IDLE_CPU_LEVEL=1
      - MONGO_DB_URI=mongodb://ditto:ditto@mongo:27017/ditto

  ditto-connectivity:
    init: true
    image: eclipse/ditto-connectivity:${DITTO_VERSION:-latest}
    mem_limit: 384m
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - ditto-policies
      - ditto-concierge
    environment:
      - TZ=UTC
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError
      - REMOTING_IDLE_CPU_LEVEL=1
      - MONGO_DB_URI=mongodb://ditto:ditto@mongo:27017/ditto

  ditto-gateway:
    init: true
    image: eclipse/ditto-gateway:${DITTO_VERSION:-latest}
    mem_limit: 384m
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - ditto-policies
      - ditto-concierge
    ports:
      - ${DITTO_GATEWAY_PORT}:8080
    environment:
      - TZ=UTC
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - REMOTING_IDLE_CPU_LEVEL=1
      - OPENJ9_JAVA_OPTIONS=-XX:+ExitOnOutOfMemoryError
      - ENABLE_DUMMY_AUTH=true
      - DEVOPS_SECURE_STATUS=false
      - GATEWAY_PUBLIC_HEALTH_SECURE=false

  ditto-swagger-ui:
    image: swaggerapi/swagger-ui:${DITTO_SWAGGER}
    volumes:
      - ./ditto/swagger/openapi:/usr/share/nginx/html/openapi:ro
      - ./ditto/swagger/swagger3-index.html:/usr/share/nginx/html/index.html:ro
      - ./ditto/images:/usr/share/nginx/html/images:ro
    command: nginx -g 'daemon off;'
    environment:
      - API_URL=/apidoc/openapi/ditto-api-2.yml

  ditto:
    image: nginx:${NGINX_VERSION}
    volumes:
      - ./ditto/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ditto/nginx.htpasswd:/etc/nginx/nginx.htpasswd:ro
      - ./ditto/nginx-cors.conf:/etc/nginx/nginx-cors.conf:ro
      - ./ditto/index.html:/etc/nginx/html/index.html:ro
      - ./ditto/images:/etc/nginx/html/images:ro
    ports:
      - ${DITTO_NGINX_PORT}:80
    depends_on:
      - ditto-gateway
      - ditto-swagger-ui
