version: "2.4"
services:

  connector-edge:
    image: ${PREFIX_IMG}/dashboard-connector-edge:${IOT_VERSION}
    ports:
      - ${CONNECTOR_EDGE_PORT}:8080
      - ${CONNECTOR_EDGE_EVENTBUS_PORT}:5000
      - ${CONNECTOR_EDGE_CLUSTER_PORT}:5701
    volumes:
      - connector-edge-data:/data
      - ./engine/connector-edge.json:/app/conf/config.json
      - ./engine/hazelcast.xml:/app/conf/hazelcast.xml
      - ./engine/eventBusKeystore.jks:/app/conf/eventBusKeystore.jks

  bios:
    image: ${PREFIX_IMG}/edge-bios:${IOT_VERSION}
    command: >-
      ./wait-for-it.sh nexus:8081 --timeout=120 -s -- ./entrypoint.sh
    mem_limit: 480m
    cpuset: "0"
    environment:
      JVM_OPTS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+UseContainerSupport -XX:+UseSerialGC -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:MaxRAM=395m -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -Xss256k -XX:ActiveProcessorCount=0
    ports:
      - ${BIOS_EVENTBUS_PORT}:5000
      - ${BIOS_CLUSTER_PORT}:5701
      - ${BIOS_GATEWAY_PORT}:8080
    volumes:
      - bios-data:/data
      - ./engine/bios.json:/app/conf/config.json
      - ./engine/hazelcast.xml:/app/conf/hazelcast.xml
      - ./engine/eventBusKeystore.jks:/app/conf/eventBusKeystore.jks

volumes:
  connector-edge-data:
    driver: local
  bios-data:
    driver: local
