version: "2.4"
services:
  zookeeper:
    image: wurstmeister/zookeeper:${ZOOKEEPER_VERSION}
    ports:
      - ${ZOOKEEPER_PORT}:2181
    volumes:
      - zk-data:/opt/zookeeper-3.4.13/data
      - zk-conf:/opt/zookeeper-3.4.13/conf

  kafka:
    image: wurstmeister/kafka:${KAFKA_VERSION}
    ports:
      - ${KAFKA_PORT}:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: "getent hosts `hostname` | cut -d' ' -f1"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://_{HOSTNAME_COMMAND}:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka-log:/kafka

  connector-kafka:
    image: ${PREFIX_IMG}/nube-dashboard-connector-sample-kafka:${IOT_VERSION}
    ports:
      - ${CONNECTOR_KAFKA_PORT}:8080
    volumes:
      - connector-kafka-data:/data
      - ./engine/connector-kafka.json:/app/conf/config.json
      - ./engine/hazelcast.xml:/app/conf/hazelcast.xml
      - ./engine/eventBusKeystore.jks:/app/conf/eventBusKeystore.jks
    depends_on:
      - kafka

volumes:
  kafka-log:
    driver: local
  zk-data:
    driver: local
  zk-conf:
    driver: local
  connector-kafka-data:
    driver: local
