version: '2'
services:
  mongo:
    image: mongo:${MONGO_VERSION}
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: sandbox
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./mongo/:/docker-entrypoint-initdb.d/
      - mongo-data:/data/db
      - mongo-cfg:/data/configdb
volumes:
  mongo-data:
    driver: local
  mongo-cfg:
    driver: local
